### ISSUE TITLE
Release ?

### ISSUE THREAD

**Issue by tdesvenain** [dveselov/pyodconverter#5]
Hi, it seems stable now, can we have a new release ?
Can i be added to the contributors list ?

Thanks !

Thomas

**Comment by tyrannosaurus** [comment]
Yes, of course!
Please, create pull request with your contact details.

**Comment by tyrannosaurus** [comment]
Version 1.8 is now available on PyPI.

**Comment by tdesvenain** [comment]
Thanks !

2014-06-27 22:26 GMT+02:00 tyrannosaurus notifications@github.com:

> Version 1.8 is now available on PyPI.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/tyrannosaurus/pyodconverter/issues/5#issuecomment-47396362
> .

## 

Thomas Desvenain

Téléphone : 09 51 37 35 18
